version: '3'
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    container_name: api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    tty: true
    stdin_open: true
    volumes:
      - ./api/:/src/app
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile
    container_name: front
    depends_on: 
      - api
    environment: 
      API_HOST: api
      API_PORT: 8000
    ports:
      - 8080:8080
    tty: true
    stdin_open: true
    volumes:
      - ./front/:/myapp
