version: '3'
services:
  sns:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 8080:8080
    tty: true
    stdin_open: true
    volumes:
      - ./:/server/
